# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
include_ext = ["go", "tmpl", "tpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend"]
delay = 1000 # Delay in milliseconds between rebuilds

[log]
time = true

[watcher]
ignore = [".git/*", "tmp/*"]
